"""empty message

Revision ID: 5d68a00a9150
Revises: 199c404a60b8
Create Date: 2026-01-29 21:53:07.701144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d68a00a9150'
down_revision = '199c404a60b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'character_id', 'location_id')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='followers_character_id_fkey'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], name='followers_location_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='followers_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'character_id', 'location_id', name='followers_pkey')
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
